kind: Service
apiVersion: v1
metadata:
  name: py-http-svc
spec:
  selector:
    app: py-http
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10000

