apiVersion: apps/v1 
kind: Deployment
metadata:
  name: py-http
spec:
  selector:
    matchLabels:
      app: py-http
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: py-http
    spec:
      serviceAccountName: default
      containers:
      - name: py-http-server
        image: "quay.io/ibm_cpd_zen/zen-python:latest"
        command: ["/bin/bash","-c"]
        args: ["cd /tmp; git clone https://github.com/sriramsrinivasangmail/pyk8s.git && pyk8s/bin/start.sh"]
        ports:
        - containerPort: 8080
        env:
          - name: MY_NODE_NAME
            valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

